/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.godilithium;

public class godilithium {
  public static void tss_buffer_free(tss_buffer buf) {
    godilithiumJNI.tss_buffer_free(tss_buffer.getCPtr(buf), buf);
  }

  public static mldsa_error mldsa_keygen_setupmsg_new(MldsaSecurityLevel level, long threshold, go_slice key_id, go_slice ids, tss_buffer setup_msg) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_setupmsg_new(level.swigValue(), threshold, go_slice.getCPtr(key_id), key_id, go_slice.getCPtr(ids), ids, tss_buffer.getCPtr(setup_msg), setup_msg));
  }

  public static mldsa_error mldsa_keygen_session_from_setup(MldsaSecurityLevel level, go_slice setup, go_slice id, Handle hnd) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_from_setup(level.swigValue(), go_slice.getCPtr(setup), setup, go_slice.getCPtr(id), id, Handle.getCPtr(hnd), hnd));
  }

  public static mldsa_error mldsa_keygen_session_input_message(Handle session, go_slice message, int[] finished) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_input_message(Handle.getCPtr(session), session, go_slice.getCPtr(message), message, finished));
  }

  public static mldsa_error mldsa_keygen_session_output_message(Handle session, tss_buffer message) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_output_message(Handle.getCPtr(session), session, tss_buffer.getCPtr(message), message));
  }

  public static mldsa_error mldsa_keygen_session_message_receiver(Handle session, go_slice message, long index, tss_buffer receiver) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_message_receiver(Handle.getCPtr(session), session, go_slice.getCPtr(message), message, index, tss_buffer.getCPtr(receiver), receiver));
  }

  public static mldsa_error mldsa_keygen_session_finish(Handle session, Handle keyshare) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_finish(Handle.getCPtr(session), session, Handle.getCPtr(keyshare), keyshare));
  }

  public static mldsa_error mldsa_keygen_session_free(Handle session) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keygen_session_free(Handle.getCPtr(session), session));
  }

  public static mldsa_error mldsa_keyshare_from_bytes(go_slice buf, Handle hnd) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keyshare_from_bytes(go_slice.getCPtr(buf), buf, Handle.getCPtr(hnd), hnd));
  }

  public static mldsa_error mldsa_keyshare_to_bytes(Handle share, tss_buffer buf) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keyshare_to_bytes(Handle.getCPtr(share), share, tss_buffer.getCPtr(buf), buf));
  }

  public static mldsa_error mldsa_keyshare_public_key(Handle share, tss_buffer buf) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keyshare_public_key(Handle.getCPtr(share), share, tss_buffer.getCPtr(buf), buf));
  }

  public static mldsa_error mldsa_keyshare_key_id(Handle share, tss_buffer buf) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keyshare_key_id(Handle.getCPtr(share), share, tss_buffer.getCPtr(buf), buf));
  }

  public static mldsa_error mldsa_keyshare_free(Handle share) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_keyshare_free(Handle.getCPtr(share), share));
  }

  public static mldsa_error mldsa_decode_key_id(go_slice setup, tss_buffer key_id) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_decode_key_id(go_slice.getCPtr(setup), setup, tss_buffer.getCPtr(key_id), key_id));
  }

  public static mldsa_error mldsa_decode_message(go_slice setup, tss_buffer message) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_decode_message(go_slice.getCPtr(setup), setup, tss_buffer.getCPtr(message), message));
  }

  public static mldsa_error mldsa_decode_party_name(go_slice setup, long index, tss_buffer message) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_decode_party_name(go_slice.getCPtr(setup), setup, index, tss_buffer.getCPtr(message), message));
  }

  public static mldsa_error mldsa_sign_setupmsg_new(MldsaSecurityLevel level, go_slice key_id, go_slice chain_path, go_slice message_hash, go_slice ids, tss_buffer setup_msg) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_setupmsg_new(level.swigValue(), go_slice.getCPtr(key_id), key_id, go_slice.getCPtr(chain_path), chain_path, go_slice.getCPtr(message_hash), message_hash, go_slice.getCPtr(ids), ids, tss_buffer.getCPtr(setup_msg), setup_msg));
  }

  public static mldsa_error mldsa_sign_session_from_setup(MldsaSecurityLevel level, go_slice setup, go_slice id, Handle share, Handle hnd) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_from_setup(level.swigValue(), go_slice.getCPtr(setup), setup, go_slice.getCPtr(id), id, Handle.getCPtr(share), share, Handle.getCPtr(hnd), hnd));
  }

  public static mldsa_error mldsa_sign_session_input_message(Handle session, go_slice message, int[] finished) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_input_message(Handle.getCPtr(session), session, go_slice.getCPtr(message), message, finished));
  }

  public static mldsa_error mldsa_sign_session_output_message(Handle session, tss_buffer message) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_output_message(Handle.getCPtr(session), session, tss_buffer.getCPtr(message), message));
  }

  public static mldsa_error mldsa_sign_session_message_receiver(Handle session, go_slice message, long index, tss_buffer receiver) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_message_receiver(Handle.getCPtr(session), session, go_slice.getCPtr(message), message, index, tss_buffer.getCPtr(receiver), receiver));
  }

  public static mldsa_error mldsa_sign_session_finish(Handle session, tss_buffer output) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_finish(Handle.getCPtr(session), session, tss_buffer.getCPtr(output), output));
  }

  public static mldsa_error mldsa_sign_session_free(Handle session) {
    return mldsa_error.swigToEnum(godilithiumJNI.mldsa_sign_session_free(Handle.getCPtr(session), session));
  }

}
