/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.godilithium;

public final class MldsaSecurityLevel {
  public final static MldsaSecurityLevel MlDsa44 = new MldsaSecurityLevel("MlDsa44", godilithiumJNI.MlDsa44_get());
  public final static MldsaSecurityLevel MlDsa65 = new MldsaSecurityLevel("MlDsa65", godilithiumJNI.MlDsa65_get());
  public final static MldsaSecurityLevel MlDsa87 = new MldsaSecurityLevel("MlDsa87", godilithiumJNI.MlDsa87_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static MldsaSecurityLevel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + MldsaSecurityLevel.class + " with value " + swigValue);
  }

  private MldsaSecurityLevel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private MldsaSecurityLevel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private MldsaSecurityLevel(String swigName, MldsaSecurityLevel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static MldsaSecurityLevel[] swigValues = { MlDsa44, MlDsa65, MlDsa87 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

