/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.godilithium;

public final class mldsa_error {
  public final static mldsa_error LIB_OK = new mldsa_error("LIB_OK");
  public final static mldsa_error LIB_INVALID_HANDLE = new mldsa_error("LIB_INVALID_HANDLE");
  public final static mldsa_error LIB_HANDLE_IN_USE = new mldsa_error("LIB_HANDLE_IN_USE");
  public final static mldsa_error LIB_INVALID_HANDLE_TYPE = new mldsa_error("LIB_INVALID_HANDLE_TYPE");
  public final static mldsa_error LIB_NULL_PTR = new mldsa_error("LIB_NULL_PTR");
  public final static mldsa_error LIB_INVALID_BUFFER_SIZE = new mldsa_error("LIB_INVALID_BUFFER_SIZE");
  public final static mldsa_error LIB_INVALID_SESSION_STATE = new mldsa_error("LIB_INVALID_SESSION_STATE");
  public final static mldsa_error LIB_UNKNOWN_ERROR = new mldsa_error("LIB_UNKNOWN_ERROR");
  public final static mldsa_error LIB_SERIALIZATION_ERROR = new mldsa_error("LIB_SERIALIZATION_ERROR");
  public final static mldsa_error LIB_INVALID_DERIVATION_PATH_STR = new mldsa_error("LIB_INVALID_DERIVATION_PATH_STR");
  public final static mldsa_error LIB_DERIVATION_ERROR = new mldsa_error("LIB_DERIVATION_ERROR");
  public final static mldsa_error LIB_SETUP_MESSAGE_VALIDATION = new mldsa_error("LIB_SETUP_MESSAGE_VALIDATION");
  public final static mldsa_error LIB_NON_EMPTY_OUTPUT_BUFFER = new mldsa_error("LIB_NON_EMPTY_OUTPUT_BUFFER");
  public final static mldsa_error LIB_SIGNGEN_ERROR = new mldsa_error("LIB_SIGNGEN_ERROR");
  public final static mldsa_error LIB_KEYGEN_ERROR = new mldsa_error("LIB_KEYGEN_ERROR");
  public final static mldsa_error _LIB_QC_ERROR = new mldsa_error("_LIB_QC_ERROR");
  public final static mldsa_error _LIB_KEY_EXPORT_ERROR = new mldsa_error("_LIB_KEY_EXPORT_ERROR");
  public final static mldsa_error LIB_INVALID_PARTY_LIST = new mldsa_error("LIB_INVALID_PARTY_LIST");
  public final static mldsa_error _LIB_INVALID_OLD_PARTY_LIST = new mldsa_error("_LIB_INVALID_OLD_PARTY_LIST");
  public final static mldsa_error _LIB_INVALID_NEW_PARTY_LIST = new mldsa_error("_LIB_INVALID_NEW_PARTY_LIST");
  public final static mldsa_error _LIB_INVALID_PUBLIC_KEY = new mldsa_error("_LIB_INVALID_PUBLIC_KEY");
  public final static mldsa_error _LIB_INVALID_PRIVATE_KEY = new mldsa_error("_LIB_INVALID_PRIVATE_KEY");
  public final static mldsa_error LIB_REJSAMPLING = new mldsa_error("LIB_REJSAMPLING");
  public final static mldsa_error LIB_ABORT_PROTOCOL_PARTY_1 = new mldsa_error("LIB_ABORT_PROTOCOL_PARTY_1", godilithiumJNI.LIB_ABORT_PROTOCOL_PARTY_1_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static mldsa_error swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + mldsa_error.class + " with value " + swigValue);
  }

  private mldsa_error(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private mldsa_error(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private mldsa_error(String swigName, mldsa_error swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static mldsa_error[] swigValues = { LIB_OK, LIB_INVALID_HANDLE, LIB_HANDLE_IN_USE, LIB_INVALID_HANDLE_TYPE, LIB_NULL_PTR, LIB_INVALID_BUFFER_SIZE, LIB_INVALID_SESSION_STATE, LIB_UNKNOWN_ERROR, LIB_SERIALIZATION_ERROR, LIB_INVALID_DERIVATION_PATH_STR, LIB_DERIVATION_ERROR, LIB_SETUP_MESSAGE_VALIDATION, LIB_NON_EMPTY_OUTPUT_BUFFER, LIB_SIGNGEN_ERROR, LIB_KEYGEN_ERROR, _LIB_QC_ERROR, _LIB_KEY_EXPORT_ERROR, LIB_INVALID_PARTY_LIST, _LIB_INVALID_OLD_PARTY_LIST, _LIB_INVALID_NEW_PARTY_LIST, _LIB_INVALID_PUBLIC_KEY, _LIB_INVALID_PRIVATE_KEY, LIB_REJSAMPLING, LIB_ABORT_PROTOCOL_PARTY_1 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

