/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.goschnorr;

public class Handle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Handle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        goschnorrJNI.delete_Handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_0(SWIGTYPE_p_int32_t value) {
    goschnorrJNI.Handle__0_set(swigCPtr, this, SWIGTYPE_p_int32_t.getCPtr(value));
  }

  public SWIGTYPE_p_int32_t get_0() {
    return new SWIGTYPE_p_int32_t(goschnorrJNI.Handle__0_get(swigCPtr, this), true);
  }

  public Handle() {
    this(goschnorrJNI.new_Handle(), true);
  }

}
