/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.goschnorr;

public interface goschnorrConstants {
  public final static int DEFAULT_TTL = goschnorrJNI.DEFAULT_TTL_get();
}
