/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.silencelaboratories.godkls;

public class tss_buffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected tss_buffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tss_buffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(tss_buffer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        godklsJNI.delete_tss_buffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPtr(SWIGTYPE_p_uint8_t value) {
    godklsJNI.tss_buffer_ptr_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getPtr() {
    long cPtr = godklsJNI.tss_buffer_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setLen(SWIGTYPE_p_uintptr_t value) {
    godklsJNI.tss_buffer_len_set(swigCPtr, this, SWIGTYPE_p_uintptr_t.getCPtr(value));
  }

  public SWIGTYPE_p_uintptr_t getLen() {
    return new SWIGTYPE_p_uintptr_t(godklsJNI.tss_buffer_len_get(swigCPtr, this), true);
  }

  public tss_buffer() {
    this(godklsJNI.new_tss_buffer(), true);
  }

}
